apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
  namespace: ecom
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30502
