apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: ecom
spec:
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 800m
      memory: 1Gi
