apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 5000
      targetPort: 15672
      nodePort: 30500
