apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: discovery
  namespace: ecom
spec:
  host: discovery
  subsets:
  - name: discovery
    labels:
      app: discovery      
##
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: config
  namespace: ecom
spec:
  host: config
  subsets:
  - name: config
    labels:
      app: config
##
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: apigateway
  namespace: ecom
spec:
  host: apigateway
  subsets:
  - name: apigateway
    labels:
      app: apigateway
##
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customer
  namespace: ecom
spec:
  host: customer
  subsets:
  - name: customer
    labels:
      app: customer
##
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order-svc
  namespace: ecom
spec:
  host: order-svc
  subsets:
  - name: order
    labels:
      app: order
##
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: item
  namespace: ecom
spec:
  host: item
  subsets:
  - name: item
    labels:
      app: item

##

