apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecom-gateway
  namespace: ecom
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecom
  namespace: ecom
spec:
  hosts:
  - "*"
  gateways:
  - ecom-gateway
  http:
  - name: customer-svc
    match:
    - uri:
        exact: /customer-svc/customers
#     - uri:
#         exact: /customer-svc/login
#     - uri:
#         exact: /login
#     - uri:
#         exact: /logout
#     - uri:
#         prefix: /api/v1/products 
    route:
    - destination:
        host: customer.ecom.svc.cluster.local
#         port:
#           number: 9080
    corsPolicy:
      allowMethods:
      - POST
  - name: customer-svc    
    match:
    - uri:
        exact: /customer-svc/login
    route:
    - destination:
        host: customer.ecom.svc.cluster.local
    corsPolicy:
      allowMethods:
      - GET
