apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  name: ecom
spec:
  storageClassName: db-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
