apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: ecom
spec:
  type: NodePort
  selector:
    app: discovery
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30501
