apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: ecom
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: parkchansu/customer-service:1.0
        ports:
        - containerPort: 8500
        env:
        - name: spring.cloud.config.uri
          value: "http://config-service:8888"
        - name: spring.cloud.config.uri
          value: "http://config-service:8888"
        - name: spring.rabbitmq.host
          value: "rabbitmq"
        - name: spring.zipkin.base-url
          value: "http://zipkin:9411"
        - name: eureka.client.serviceUrl.defaultZone
          value: "http://discovery-service:8761/eureka/"
        - name: logging.file
          value: "/api-logs/users-ws.log"
